#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php: [5.6, 7]

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - phpunit -c phpunit.xml.dist --testdox

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true
